name: raster_compare
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - gdal
  - ipython
  - matplotlib
  - numba
  - numexpr
  - palettable
  - pandas
  - pillow
  - pip
  - python-pdal
  - statsmodels
  - pip:
      - opencv-python
      - matplotlib-scalebar
