name: raster_compare
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - gdal=2.4
  - ipython
  - matplotlib
  - pandas
  - pillow
  - pip
  - python-pdal
  - statsmodels
  - pip:
      - opencv-python
